# Generated by Django 5.1 on 2025-01-09 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=255)),
                ('snapshot_name', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(choices=[('selected_time', 'On Selected Time'), ('on_demand', 'On Demand')], default='selected_time', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('include_ram', models.BooleanField(default=False)),
                ('manual_mode', models.BooleanField(default=False)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_snapshots', to=settings.AUTH_USER_MODEL)),
                ('approvers_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_approvals', to='auth.group')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_snapshots', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApproverAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('none', 'No Action'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10)),
                ('action_time', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('snapshot_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_actions', to='request_snapshot_app.snapshotrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='snapshotrequest',
            index=models.Index(fields=['status'], name='request_sna_status_f756cf_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshotrequest',
            index=models.Index(fields=['vm_name'], name='request_sna_vm_name_f12689_idx'),
        ),
        migrations.AddIndex(
            model_name='snapshotrequest',
            index=models.Index(fields=['created_at'], name='request_sna_created_4d53de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approveraction',
            unique_together={('snapshot_request', 'approver')},
        ),
    ]
