# Generated by Django 5.1 on 2024-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotRequest',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vm_name', models.CharField(max_length=255)),
                ('snapshot_name', models.CharField(max_length=255)),
                ('include_ram', models.BooleanField(default=False)),
                ('reasoning', models.TextField()),
                ('date_time', models.DateTimeField(null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('substatus', models.CharField(default='Pending Approval', max_length=50)),
            ],
        ),
    ]
