# Generated by Django 5.1 on 2024-09-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_panel', '0002_alter_snapshotrequest_date_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='snapshotrequest',
            table='snapshots',
        ),
    ]
